    export default images = {
        logo: require('./assets/logo.svg'),
        farmer: require('./assets/farmer.svg'),
        barn : require('./assets/barn.svg'),
        mound : require('./assets/mound.svg'),
        stackshort : require('./assets/stackshort.svg'),
        stacktall : require('./assets/stacktall.svg'),
        market : require('./assets/market.svg'),
        tractor : require('./assets/tractor.svg'),
        hay : require('./assets/hay.svg'),
        profile : require("./assets/avatar.svg"),
        ellispe : require("./assets/ellipse.svg"),
        greenbar : require("./assets/greenbar.svg"),
        photo : require("./assets/1.svg"),
    }