export { default as DealerLogin } from './dealer/DealerLogin'
export { default as FarmerLogin } from './farmer/FarmerLogin'
export { default as FarmerDashboard } from './farmer/FarmerDashboard'
export { default as FarmerRegister } from './farmer/FarmerRegister'
export { default as DealerRegister } from './dealer/DealerRegister'
export { default as Splash } from './Switch'
export {default as Loading} from './Loading'
export {default as Register} from './Register'
export {default as WorkInfo} from './WorkInfo'
export {default as Login} from './Login'
