# Generated by Django 5.0.3 on 2024-03-08 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Fci_App", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="crop",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="crop_register",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="dealer",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="farmer",
        ),
        migrations.DeleteModel(
            name="crop_register",
        ),
        migrations.DeleteModel(
            name="transaction",
        ),
        migrations.DeleteModel(
            name="user",
        ),
    ]
