# Generated by Django 5.0.3 on 2024-03-08 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Fci_App", "0002_delete_crop_remove_transaction_crop_register_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("msp", models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Crop_register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("quantity", models.IntegerField(max_length=10)),
                (
                    "dealer_type",
                    models.CharField(
                        choices=[("p", "private"), ("g", "govt"), ("b", "both")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=60, unique=True)),
                ("password", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[("kisan", "kisan"), ("dealer", "dealer")],
                        max_length=50,
                    ),
                ),
                (
                    "dealer_type",
                    models.CharField(
                        choices=[
                            ("private", "private"),
                            ("govt", "govt"),
                            ("kisan", "kisan"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting_for_farmer", "Waiting for Farmer"),
                            ("delivered", "Delivered"),
                            ("deal_done", "Deal Done"),
                            ("payment_done", "Payment Done"),
                            ("late", "Late"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.IntegerField(max_length=10)),
                ("deal_Date", models.DateTimeField()),
                (
                    "crop_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Fci_App.crop_register",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_as_dealer",
                        to="Fci_App.user",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_as_farmer",
                        to="Fci_App.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crop_register",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crop_registered",
                to="Fci_App.user",
            ),
        ),
    ]
