# Generated by Django 5.0.3 on 2024-03-10 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fci_App', '0004_alter_user_dealer_type_alter_user_id_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop_register',
            name='farmer_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop_register',
            name='farmer_name',
            field=models.CharField(default='abishek', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('waiting_for_farmer', 'Waiting for Farmer'), ('rejected', 'rejected'), ('delivered', 'Delivered'), ('deal_done', 'Deal Done'), ('payment_done', 'Payment Done'), ('late', 'Late')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60),
        ),
    ]
